config/routes.rb
Rails.application.routes.draw do
  get 'reviews/show'
  get 'reviews/new'
  get 'reviews/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :ingredients
    resources :doses
    resources :reviews
  end

  root to: 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, :scope => :ingredient_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail

  validates :star, inclusion: { in: (0..5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :destroy, :edit, :update]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @ingredient = @cocktail.ingredients
    @dose = Dose.new
    @dose.cocktail_id = @cocktail.id
    @doses = @cocktail.doses
    @review = Review.new
    @review.cocktail_id = @cocktail.id
    @reviews = @cocktail.reviews
  end

  def new
    @cocktail = Cocktail.new
    @cocktails = Cocktail.all
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save
    redirect_to cocktails_path
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktails_path
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [ :show, :destroy, :edit, :update ]
  def index
  end

  def new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    @dose.save
    redirect_to cocktail_path(@dose.cocktail)
  end

  def edit
  end

  private

  def set_dose
    @dose = dose.find(params[:id])
  end

  def dose_params
    params.require(:dose).permit(:amount, :description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def show
    @reviews = Review.all
  end

  def new
  end

  def create
    @review = Review.new(review_params)
    @review.cocktail = Cocktail.find(params[:cocktail_id])
    @review.save
    redirect_to cocktail_path(@review.cocktail)
  end

  private

  def review_params
    params.require(:review).permit(:user_name, :description, :star)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/delete.html.erb
<h1>Cocktails#delete</h1>
<p>Find me in app/views/cocktails/delete.html.erb</p>

app/views/cocktails/edit.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
<% end %>

app/views/cocktails/index.html.erb
<div class="banner">
  <div class="container">
    <h1 id="page-title">Best CocktailBar <strong>in Town!</strong></h1>
  </div>
  <p><%= link_to "Add new cocktail", new_cocktail_path, class: "create"  %></p>
</div>

<div class = "container display">
  <% @cocktails.each do |cocktail| %>
  <div class = "card-container" data-aos="fade-up" data-aos-duration="1000">
    <div class = "cards">
      <p><span>Name:</span> <%= cocktail.name %></p>
      <div id="link-show">
        <%= link_to "more details", cocktail_path(cocktail), class: "btn btn-info button-card" %>
      </div>
      <div id="buttons-on-top-1">
        <%= link_to cocktail_path(cocktail), method: :delete, data: { confirm: "You really want to delete this amazing cocktail?"} do   %>
          <i class="fas fa-minus-square button-action"></i>
        <% end %>
      </div>
      <%= cl_image_tag cocktail.photo, height: 300, width: 400, crop: :fill, class: "avatar-large" %>
    </div>
  </div>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<h1 id="title-new">Complete the form to add a new Cocktail to the list!</h1>
<%= link_to "Back to list", cocktails_path, class: "btn btn-primary back-to-list" %>

<div id="create-grid">
  <div id ="create-cocktail">
    <%= simple_form_for @cocktail do |f| %>
      <%= f.input :name%>
      <%= f.input :photo%>
      <%= f.input :photo_cache, as: :hidden %>
      <div class="btn btn-primary">
        <%= f.button :submit, class: "create-cocktail-button"%>
      </div>
    <% end %>
  </div>
  <div id = "list-create">
    <h3>Here are the already created cocktails</h3>
    <div id ="all-cocktails-create">
      <% @cocktails.each do |cocktail| %>
      <p><%= cocktail.name %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div id="show">
  <%= link_to "Back to List", cocktails_path, class: "btn btn-primary back-to-list" %>
  <h1><%= @cocktail.name %></h1>
  <div id="cocktail-main-info">
    <div id = "image-show">
      <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>
      <%= link_to edit_cocktail_path(@cocktail) do   %>
        <i class="fas fa-pen button-action"></i>
      <% end %>
    </div>
    <div id="ingredients">
      <h4><i class="fas fa-glass-martini-alt"></i> Recipee:</h4>
      <% i = 1 %>
      <% @doses.each do |dose| %>
        <p><%= i %> <i class="fas fa-arrow-right"></i> <%= dose.amount %> <%= dose.description %> <%= dose.ingredient.name %></p>
      <% i += 1 %>
      <% end %>
    </div>
    <div id="reviews">
      <h4><i class="far fa-comment-dots"></i> Reviews:</h4>
      <div id="review-box">
        <% @reviews.each do |review| %>
          <div id="chat-box">
            <p><span>User Name: </span><%= review.user_name %></p>
            <p><span>Review: </span><%= review.description %></p>
            <p><span>Rating: </span><%= '⭐' * review.star %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample" id="expand-form">
    Create a new dose!
  </a>
  <div class = "form-box">
    <div class="collapse" id="collapseExample">
      <div class="card card-body">
        <h4>Fill in the form to add a dose!</h4>
        <%= simple_form_for [@cocktail, @dose] do |f| %>
          <div class="form-group">
            <%= f.input :amount, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.input :description, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.association :ingredient, class: 'form-control' %>
          </div>
            <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
  <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample2" role="button" aria-expanded="false" aria-controls="collapseExample2" id="expand-form-review">
    Create a new Review!
  </a>
  <div class = "form-box">
    <div class="collapse" id="collapseExample2">
      <div class="card card-body">
        <h4>Fill in the form to add a Review!</h4>
        <%= simple_form_for [@cocktail, @review] do |f| %>
          <div class="form-group">
            <%= f.input :user_name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.input :description, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.input :star, class: 'form-control' %>
          </div>
            <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/doses/edit.html.erb
<h1>Doses#edit</h1>
<p>Find me in app/views/doses/edit.html.erb</p>

app/views/doses/index.html.erb
<h1>Doses#index</h1>
<p>Find me in app/views/doses/index.html.erb</p>

app/views/doses/new.html.erb
<%= simple_form_for @dose do |f| %>
  <%= f.input :amount %>
  <%= f.input :description %>
  <%= f.input @ingredients %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css?family=Yesteryear&display=swap" rel="stylesheet">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
  </head>

  <body>
    <%= yield %>
    <script>AOS.init()</script>
  </body>
</html>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>